# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
program: train_sb3_wandb_td3.py
method: grid
name: rel_ik_sb3_td3_ur5e_lift_cube_0_05
metric:
  goal: maximize
  name: rollout/ep_rew_mean

parameters:
  seed:
    value: 42

  device:
    value: "cuda:0"

  n_timesteps: # iteration * n_steps * nenvs: 400 * 64 * 8192 = 209715200
    value: 209715200

  policy:
    value: 'MlpPolicy'

  batch_size:
    values: [256, 512] 

  gamma:
    value: 0.95

  learning_rate:
    values: [1e-4, 3e-4]

  train_freq:
    value: 4

  gradient_steps:
    value: 4

  buffer_size: 
    value: 1000000

  policy_delay:
    value: 2

  learning_starts: 
    value: 1000

  tau: 
    value: 0.02

  target_policy_noise:
    values: [0.2, 0.4]

  target_noise_clip:
    value: 0.5

  action_noise:
    value: NormalActionNoise

  # replay_buffer_class: 
  #   value: "HerReplayBuffer"

  # replay_buffer_kwargs: 
  #   value: "dict(goal_selection_strategy='future', n_sampled_goal=4)"

  policy_kwargs:
    parameters:
      activation_fn: 
        values: ['nn.ELU', 'nn.ReLU', 'nn.Tanh']
      net_arch:
        value: [256, 256]


  normalize_input:
    value: False

  normalize_value:
    value: False

  clip_obs:
    value: 50.0