# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml
seed: 42
n_timesteps: 209715200 
policy: 'MlpPolicy'
batch_size: 256
gamma: 0.95
learning_rate: !!float 3e-4
train_freq: 4
gradient_steps: 4
buffer_size: 1000000
policy_delay: 2
learning_starts: 1000
tau: 0.02
target_policy_noise: 0.2
target_noise_clip: 0.5
action_noise: NormalActionNoise
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=dict(pi=[256, 256], vf=[256, 256])
                )"

# Uses VecNormalize class to normalize obs
normalize_input: False
# Uses VecNormalize class to normalize rew
normalize_value: False
clip_obs: 50.0
